---
title: "DataTidying"
author: "Christina Fossum"
date: "2025-10-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(writexl)
library(knitr)
library(EnvStats)

# Header loading function
load_headers <- function(directory_path, pattern) {
  list_files <- list.files(path = directory_path, pattern = pattern, full.names = TRUE)
  data_list <- lapply(list_files, function(file) {
    file_data <- read.csv(file) %>% select(1:10) %>% filter(Visited == "True")
    file_data <- file_data %>% mutate(Comment = "")
  })
  return(do.call(rbind, data_list))
}

load_data <- function(directory_path, pattern) {
  list_files <- list.files(path = directory_path, pattern = pattern, full.names = TRUE)
  data_list <- lapply(list_files, function(file) {
    if (file.info(file)$size == 0) return(NULL)
    file_data <- tryCatch({
      read.csv(file, skip = 3) %>% mutate(Comment = "")
    }, error = function(e) {
      message("Error reading file: ", file, " - skipping this file.")
      return(NULL)
    })
    return(file_data)
  })
  do.call(rbind, data_list[!sapply(data_list, is.null)])
}
directory_path <- "WestSideData/pico_2025/"
# load data (Cover - Points)
cover_df <- load_data(directory_path, "_Cover - Points \\(metric\\)\\.csv$")
cover_headers <-load_headers(directory_path, "_Cover - Points \\(metric\\)\\.csv$")

directory_path2 <- "WestSideData/pico_old/"
cover_df2 <- load_data(directory_path2, "_Cover - Points \\(metric\\)\\.csv$")
cover_headers2 <-load_headers(directory_path2, "_Cover - Points \\(metric\\)\\.csv$")

cover_df <- cover_df %>% mutate(NumTransects = 2,
                                TranLength_m = 20,
                                PtsPerTransect = 20)
cover_df2 <- cover_df2 %>% mutate(NumTransects = 1,
                                 TranLength_m = 50,
                                 PtsPerTransect = 166)

cover <- rbind(cover_df, cover_df2)

##############################




# load data (Surface Fuels - Fine)
fuelsfine_df <- load_data(directory_path, "_Surface Fuels - Fine.csv$")
fuelsfine_headers <-load_headers(directory_path, "_Surface Fuels - Fine.csv$")

# load data (Surface Fuels - 1000Hr)
fuels1000_df <- load_data(directory_path, "_Surface Fuels - 1000Hr.csv$")
fuels1000_headers <-load_headers(directory_path, "_Surface Fuels - 1000Hr.csv$")

# load data (Surface Fuels - Duff/Litter)
fuelsDL_df <- load_data(directory_path, "_Surface Fuels - Duff_Litter.csv$")
fuelsDL_headers <-load_headers(directory_path, "_Surface Fuels - Duff_Litter.csv$")

# load data (Trees - Individuals)
trees_df <- load_data(directory_path, "_Trees - Individuals \\(metric\\)\\.csv$")

list <- list.files(path = directory_path, pattern = "_Trees - Individuals \\(metric\\)\\.csv$", full.names = TRUE)
trees_headers <- lapply(list, function(file) read.csv(file, nrows = 1))
trees_headers <- do.call(rbind, trees_headers)




# load data (Seedlings)
seedling_df <- load_data(directory_path, "_Density - Quadrats \\(metric\\)\\.csv$")
seedling_headers <-load_headers(directory_path, "_Density - Quadrats \\(metric\\)\\.csv$")

# Load data (shrubs)
shrub_df <- load_data(directory_path, "_Density - Belts \\(metric\\)\\.csv$")
shrub_headers <- load_headers(directory_path, "_Density - Belts \\(metric\\)\\.csv$")





```